version: "3.3"

# Lista de Puertos:configs:
#   - 7001:9091 => transmission
#   - 7002:8989 => sonarr       OK
#   - 7003:9696 => prowlarr     OK
#   - 7004:5055 => Jellyseerr   OK
#   - 7005:7878 => Radarr       OK
#   - 7006:8096 => Jellyfin     OK
#   - 7007:80   => Nextcloud    OK
#   - 7009:80   => Vaultwarden 
#   - 7010:5000 => Kavita 
services:

## Files, books && security 
# Vaultwardens
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
          ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - ${BBDD_PATH}vaultwarden/data:/data/:rw
    ports:
      - 7008:80
    restart: unless-stopped
    env_file:
      - .env

# Kavita

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${CONFIG_PATH}kavita/config:/config
      - ${BBDD_PATH}kavita/data:/data:rw 
    ports:
      - 7009:5000
    restart: unless-stopped
    env_file:
      - .env

# Nextcloud
  db:
    image: mariadb:latest  
    container_name: mariadb            
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssw0rd
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "7007:80"
      - "6543:443"
    links:
      - db
    volumes:
      - ${CONFIG_PATH}nextcloud/config:/var/www/html/config:rw
      - ${CONFIG_PATH}nextcloud/custom_apps:/var/www/html/custom_apps:rw
      - ${CONFIG_PATH}nextcloud/themes:/var/www/html/themes:rw
      # Archivos y documentos
      - ${BBDD_PATH}nextcloud/data:/var/www/html/data:rw
    environment:
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    env_file:
      - .env

## Mediaserver
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ARRPATH_CONFIG}transmission/config:/config
      - ${ARRPATH_FILES_TRANSMISSION}:/tvseries
      - ${ARRPATH_FILES_TRANSMISSION}:/movies
      - ${ARRPATH_FILES_TRANSMISSION}:/music
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 7001:9091
    
    restart: unless-stopped
    env_file:
      - .env


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 7002:8989 
    volumes:
      - ${ARRPATH_CONFIG}sonarr/config:/config
      - ${ARRPATH_FILES}tvseries:/tvseries
    restart: unless-stopped
    env_file:
      - .env



  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 7003:9696 
    volumes:
      - ${ARRPATH_CONFIG}prowlarr/config:/config
    restart: unless-stopped
    env_file:
      - .env


  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 7004:5055
    volumes:
      - ${ARRPATH_CONFIG}jellyseerr/config:/app/config
      - ${ARRPATH_FILES}tvseries:/tvseries
      - ${ARRPATH_FILES}movies:/movies
      - ${ARRPATH_FILES}music:/music
    restart: unless-stopped
    env_file:
      - .env



  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 7005:7878 
    volumes:
      - ${ARRPATH_CONFIG}radarr/config:/config
      - ${ARRPATH_FILES}movies:/movies
    restart: unless-stopped
    env_file:
      - .env




  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=http://192.168.0.152 #optional

    ports:
      - 7006:8096
    volumes:
      - ${ARRPATH_CONFIG}jellyfin/config:/config
      - ${ARRPATH_FILES}tvseries:/data/tvshows
      - ${ARRPATH_FILES}movies:/data/movies
      - ${ARRPATH_FILES}music:/data/music
    restart: unless-stopped
    env_file:
      - .env

